const names = [
  "Monte Tufts",
  "Robert Dewey",
  "Ford Bowen",
  "Joel Muller",
  "Dewey Williams",
  "Leonard Preston",
  "Lindsey Schneider",
  "Tobias Durwood",
  "Morgan Carter",
  "August Valentine",
  "Lavina Williams",
  "Theresa Smith",
  "Violet Gardner",
  "Marian Morse",
  "Jane Clinton",
  "Marion Muller",
  "Cora Wolcott",
  "Grace Hawthorne",
  "Lena Miller",
  "Enola Perry",
  "Urnugar",
  "Enmempsim",
  "Anaziar",
  "Ukar",
  "Asutum",
  "Adarter",
  "Aros",
  "Arsipal",
  "Uralar",
  "Sinmelu",
  "Suna",
  "Saba",
  "Ninli",
  "Ninhub",
  "Nanna",
  "Ninsid",
  "Arun",
  "Ninla",
  "Eshkit",
  "Abil",
  "Tjeruia",
  "Tenebty",
  "Nesatna",
  "Tetahuy",
  "Irenkhet",
  "Nofrasi",
  "Tishre",
  "Mereti",
  "Wenaty",
  "Abamel",
  "Nefankha",
  "Rehere",
  "Herse",
  "Amoser",
  "Menamaya",
  "Aruher",
  "Genuta",
  "Djedkheri",
  "Munemu",
  "Merase",
  "Kelvin Carlisle",
  "Luke Carter",
  "Arthur Atwater",
  "Rev. Karl Tanner",
  "Sigmund Eaton",
  "Martin Webb",
  "Dennis Mercer",
  "James Davison",
  "Christopher Carter",
  "Armand Maverick",
  "Lydia Ward",
  "Pauline Monahan",
  "Catherine Tanner",
  "Estelle Paine",
  "Elva Woodbury",
  "Sophie Valentine",
  "Amanda Archer",
  "Joan Caldwell",
  "Pauline Conrad",
  "Hilda Burroughs",
  "Voon-Rhotha",
  "Ytho-Nyogthoa",
  "Cthoa-Ogthath",
  "Ykranan",
  "Sha-Cykrath",
  "Cykretha",
  "Ach-Nilei",
  "Ghantulzscha",
  "Ath-Ubboth",
  "Akheep",
  "The Eltdown Shards",
  "The Articles of Bexle",
  "The Vision of al-Jy",
  "The Book of Azathoth",
  "The Book of Giso",
  "The Rites of Hadnu",
  "The Enchiridion of Ugannar",
  "The Enchiridion of Quauhpopoct",
  "The Rites of Wardsav",
  "The Tome of Flesh",
  "Loren Norman",
  "Corbin Gardner",
  "Luke Randall",
  "Jasper Morse",
  "Addison Dyer",
  "Montgomery Hill",
  "Karl Dennis",
  "Lyndon Stuart",
  "Tony Godfrey",
  "Dr. Nicodemus Lane",
  "Marion Radcliffe",
  "Irene Bennett",
  "Marion Fuller",
  "Shirley West",
  "Viola Capwell",
  "Aileen Mackenzie",
  "Lois Nichols",
  "Patricia Stuart",
  "Doris Ashley",
  "Lena Akeley",
];


export default function getRandomName() {
  if (names.length == 0){
    return "Steve Jobs";
  }

  const randomIndex = Math.floor(Math.random() * names.length);
  
  const selected = names[randomIndex];

  names.splice(randomIndex, 1);

  return selected;
}
